language: 'node_js'
node_js:
  - "8"
before_script:
  - npm install
script:
  - set NODE_ENV=production && webpack
cache:
  directories:
    - "node_modules"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: cb0174619eade9c03210c1b6215f67d681479b4d
  on:
    branch: master
